version: '2.1'
services:
  apache-php:
    image: nimmis/apache-php7
    ports:
      - "12345:80"
    volumes:
      - ./src:/var/www/html/
      - ./vendor:/var/www/vendor/
  redis:
    image: redis

# (EXTENDED-HA)
#  master:

#  slave:

#  sentinel:

