version: '2'
services:
  apache-php:
    image: nimmis/apache-php7
    ports:
      - "12345:80"
    volumes:
      - ./src:/var/www/html/
      - ./vendor:/var/www/vendor/
  master:
    image: redis
  slave:
    image: redis
    command: redis-server --slaveof master 6379
  sentinel:
    image: redis
    command:
      - redis-sentinel
      - /dev/null
      - --sentinel monitor chatapp master 6379 2
      - --sentinel down-after-milliseconds chatapp 5000
      - --sentinel config-epoch chatapp 0
